Prueba/PruebaWeb/Models/PruebaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PruebaWeb.Models
{
    public class PruebaViewModel
    {
        public string valPrueba { get; set; }
    }
}

Prueba/PruebaWeb/Controllers/PruebaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Runtime.InteropServices;

namespace PruebaWeb.Controllers
{
    public class PruebaController : Controller
    {
        
        public ActionResult CaesarEncriptar(string clave, HttpPostedFileBase postedFile)
        {
            string rutaArchivo = string.Empty;
            //el siguiente if permite seleccionar un archivo en específico
            if (postedFile != null)
            {
                string ruta = Server.MapPath("");
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }

                rutaArchivo = ruta + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);

               
                Data.Caesar.Instance.ElChecha(postedFile, ruta, clave);
                byte[] ByteArchivos = new byte[postedFile.ContentLength];
                postedFile.InputStream.Read(ByteArchivos, 0, ByteArchivos.Length);
                return File(ByteArchivos, System.Net.Mime.MediaTypeNames.Application.Octet, postedFile.FileName);
            }
            return View();
        }
        public ActionResult CaesarDesEncriptar(HttpPostedFileBase postedFile, string clave)
        {
            string rutaArchivo = string.Empty;
            //el siguiente if permite seleccionar un archivo en específico
            if (postedFile != null)
            {
                string ruta = Server.MapPath("");
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }

                rutaArchivo = ruta + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);

                
                Data.Caesar.Instance.DesencriptarChecha(postedFile, ruta, clave);
                byte[] ByteArchivos = new byte[postedFile.ContentLength];
                postedFile.InputStream.Read(ByteArchivos, 0, ByteArchivos.Length);
                return File(ByteArchivos, System.Net.Mime.MediaTypeNames.Application.Octet, postedFile.FileName);
            }
            return View();
        }
        public ActionResult ZigZagEncriptar(HttpPostedFileBase postedFile, double? clave)
        {
            string rutaArchivo = string.Empty;
            //el siguiente if permite seleccionar un archivo en específico
            if (postedFile != null)
            {
                string ruta = Server.MapPath("");
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }

                rutaArchivo = ruta + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);

                
                Data.ZigZag.Instance.EncriptarZigZag(postedFile, ruta, clave);
                byte[] ByteArchivos = new byte[postedFile.ContentLength];
                postedFile.InputStream.Read(ByteArchivos, 0, ByteArchivos.Length);
                return File(ByteArchivos, System.Net.Mime.MediaTypeNames.Application.Octet, postedFile.FileName);
            }
            return View();
        }

        public ActionResult DesencriptarZigZag(HttpPostedFileBase postedFile, double? clave1 )
        {
            string rutaArchivo = string.Empty;
            //el siguiente if permite seleccionar un archivo en específico
            if (postedFile != null)
            {
                string ruta = Server.MapPath("");
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }

                rutaArchivo = ruta + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);


                Data.ZigZag.Instance.DesencriptarZigZag(postedFile, ruta, clave1);
                byte[] ByteArchivos = new byte[postedFile.ContentLength];
                postedFile.InputStream.Read(ByteArchivos, 0, ByteArchivos.Length);
                return File(ByteArchivos, System.Net.Mime.MediaTypeNames.Application.Octet, postedFile.FileName);
            }
            return View();
        }
        public ActionResult SDESEncriptar(string clave, HttpPostedFileBase postedFile)
        {
            string rutaArchivo = string.Empty;
            //el siguiente if permite seleccionar un archivo en específico
            if (postedFile != null)
            {
                string ruta = Server.MapPath("");
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }

                rutaArchivo = ruta + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);


                Data.SDES.Instance.CodificarSDES(postedFile, ruta, clave);
                byte[] ByteArchivos = new byte[postedFile.ContentLength];
                postedFile.InputStream.Read(ByteArchivos, 0, ByteArchivos.Length);
                return File(ByteArchivos, System.Net.Mime.MediaTypeNames.Application.Octet, postedFile.FileName);
            }
            return View();
        }
        public ActionResult SDESDesencriptar(HttpPostedFileBase postedFile, string clave)
        {
            string rutaArchivo = string.Empty;
            //el siguiente if permite seleccionar un archivo en específico
            if (postedFile != null)
            {
                string ruta = Server.MapPath("");
                if (!Directory.Exists(ruta))
                {
                    Directory.CreateDirectory(ruta);
                }

                rutaArchivo = ruta + Path.GetFileName(postedFile.FileName);
                string extension = Path.GetExtension(postedFile.FileName);


                Data.SDES.Instance.DecodificarSDES(postedFile, ruta, clave);
                byte[] ByteArchivos = new byte[postedFile.ContentLength];
                postedFile.InputStream.Read(ByteArchivos, 0, ByteArchivos.Length);
                return File(ByteArchivos, System.Net.Mime.MediaTypeNames.Application.Octet, postedFile.FileName);
            }
            return View();
        }
    }
}

Prueba/PruebaWeb/Views/Prueba/CaesarDesEncriptar.cshtml
@{
    ViewBag.Title = "CaesarDesEncriptar";
}

<h2>CaesarDesEncriptar</h2>
@using (Html.BeginForm("CaesarDesEncriptar", "Prueba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Index</h2>

    <br /><b><p align="left">Ingrese la clave</p></b>
    <input type="text" name="clave" />

    <br />
    <br />
    <br /><b><p align="left">Suba su archivo a desencriptar</p></b>
    @Html.TextBox("postedFile", "", new { type = "file" })
    <br />
    @ViewBag.Message
    <input type="submit" value="Subir" />
}

Prueba/PruebaWeb/Views/Prueba/CaesarEncriptar.cshtml
@{
    ViewBag.Title = "CaesarEncriptar";
}

<h2>CaesarEncriptar</h2>
@using (Html.BeginForm("CaesarEncriptar", "Prueba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Index</h2>

    <br /><b><p align="left">Ingrese la clave</p></b>
    <input type="text" name="clave" />

    <br />
    <br />
    <br /><b><p align="left">Suba su archivo a encriptar</p></b>
    @Html.TextBox("postedFile", "", new { type = "file" })
    <br />
    @ViewBag.Message
    <input type="submit" value="Subir" />
}

Prueba/PruebaWeb/Views/Prueba/DesencriptarZigZag.cshtml
@{
    ViewBag.Title = "DesencriptarZigZag";
}

<h2>DesencriptarZigZag</h2>
@using (Html.BeginForm("DesencriptarZigZag", "Prueba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Index</h2>

    <br /><b><p align="left">Ingrese la clave</p></b>
    <input type="text" name="clave" />

    <br />
    <br />
    <br /><b><p align="left">Suba su archivo a desencriptar</p></b>
    @Html.TextBox("postedFile", "", new { type = "file" })
    <br />
    @ViewBag.Message
    <input type="submit" value="Subir" />
}

Prueba/PruebaWeb/Views/Prueba/Index.cshtml
@model PruebaWeb.Models.PruebaViewModel

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("CaesarEncriptar", "Prueba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Index</h2>

    <br /><b><p align="left">Ingrese la clave</p></b>
    <input type="text" name="prueba2" />

    <br /><br /><br /><b><p align="left">Suba su archivo a encriptar</p></b>
    @Html.TextBox("file", "", new { type = "file" }) <br />
    @ViewBag.Message
    <input type="submit" value="Subir" />
}

Prueba/PruebaWeb/Views/Prueba/Index2.cshtml
@{
    ViewBag.Title = "ZigZag";
}

<h2>Index2</h2>

Prueba/PruebaWeb/Views/Prueba/SDESDesencriptar.cshtml
@{
    ViewBag.Title = "SDESDesencriptar";
}

<h2>SDESDesencriptar</h2>
@using (Html.BeginForm("SDESDesencriptar", "Prueba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Index</h2>

    <br /><b><p align="left">Ingrese la clave, un numero de 0 a 1023</p></b>
    <input type="text" name="clave" />

    <br />
    <br />
    <br /><b><p align="left">Suba su archivo a desencriptar</p></b>
    @Html.TextBox("postedFile", "", new { type = "file" })
    <br />
    @ViewBag.Message
    <input type="submit" value="Subir" />
}

Prueba/PruebaWeb/Views/Prueba/SDESEncriptar.cshtml
@{
    ViewBag.Title = "SDESEncriptar";
}

<h2>SDESEncriptar</h2>
@using (Html.BeginForm("SDESEncriptar", "Prueba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Index</h2>

    <br /><b><p align="left">Ingrese la clave, un numero de 0 a 1023</p></b>
    <input type="text" name="clave" />

    <br />
    <br />
    <br /><b><p align="left">Suba su archivo a encriptar</p></b>
    @Html.TextBox("postedFile", "", new { type = "file" })
    <br />
    @ViewBag.Message
    <input type="submit" value="Subir" />
}

Prueba/PruebaWeb/Views/Prueba/ZigZag.cshtml
@{
    ViewBag.Title = "ZigZag";
}

<h2>ZigZag</h2>
@using (Html.BeginForm("CaesarEncriptar", "Prueba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Index</h2>

    <br /><b><p align="left">Ingrese la clave</p></b>
    <input type="text" name="clave" />

    <br />
    <br />
    <br /><b><p align="left">Suba su archivo a encriptar</p></b>
    @Html.TextBox("postedFile", "", new { type = "file" })
    <br />
    @ViewBag.Message
    <input type="submit" value="Subir" />
}

Prueba/PruebaWeb/Views/Prueba/ZigZagEncriptar.cshtml
@{
    ViewBag.Title = "ZigZagEncriptar";
}

<h2>ZigZagEncriptar</h2>
@using (Html.BeginForm("ZigZagEncriptar", "Prueba", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <h2>Index</h2>

    <br /><b><p align="left">Ingrese la clave</p></b>
    <input type="text" name="clave" />

    <br />
    <br />
    <br /><b><p align="left">Suba su archivo a encriptar</p></b>
    @Html.TextBox("postedFile", "", new { type = "file" })
    <br />
    @ViewBag.Message
    <input type="submit" value="Subir" />
}

Prueba/PruebaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Lab3", "Index", "Prueba", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("EncriptarCaesar", "CaesarEncriptar", "Prueba")</li>
                    <li>@Html.ActionLink("DesencriptarCesar", "CaesarDesEncriptar", "Prueba")</li>
                    <li>@Html.ActionLink("EncriptarZigZag", "ZigZagEncriptar", "Prueba")</li>
                    <li>@Html.ActionLink("DesencriptarZigZag", "DesencriptarZigZag", "Prueba")</li>
                    <li>@Html.ActionLink("EncriptarSDES", "SDESEncriptar", "Prueba")</li>
                    <li>@Html.ActionLink("DesencriptarSDES", "SDESDesencriptar", "Prueba")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>